In [1]:
print("Hello World!")

Hello World!


In [2]:
import torch

print(torch.__version__)

2.0.1+cu118


### Tensors Intro
 - Creating tensors

#### Links
 - [Quickstart](https://pytorch.org/tutorials/beginner/basics/quickstart_tutorial.html)
 - [Tensors](https://pytorch.org/tutorials/beginner/basics/tensorqs_tutorial.html)

In [3]:
# scalar
scalar = torch.tensor(7)

scalar

tensor(7)

In [4]:
scalar.dim()

0

In [5]:
scalar.item()

7

In [6]:
# Vector
vector = torch.tensor([7, 7])
vector

tensor([7, 7])

In [7]:
vector.dim()

1

In [8]:
vector.shape

torch.Size([2])

In [9]:
# MATRIX

matrix = torch.tensor([[7, 8], [9, 10]])
matrix

tensor([[ 7,  8],
        [ 9, 10]])

In [10]:
matrix.dim()

2

In [11]:
matrix[1]

tensor([ 9, 10])

In [12]:
matrix.shape

torch.Size([2, 2])

In [13]:
# TENSOR

tensor = torch.tensor([[[[1, 2, 3], [3, 4, 7], [5, 6, 9]]]])
tensor.shape

torch.Size([1, 1, 3, 3])

### Random tensors

In [14]:
# Create a random tensor of shape (3, 4)

random_tensor = torch.rand(1, 3, 4)
random_tensor

tensor([[[0.3644, 0.6915, 0.8088, 0.1760],
         [0.9756, 0.4456, 0.4390, 0.1896],
         [0.4809, 0.9077, 0.5290, 0.0725]]])

In [15]:
# Create a random tensor with similar shape of image tensor

random_image_size_tensor = torch.rand(224, 224, 3) # height, width, color channels (R, G, B)
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([224, 224, 3]), 3)

### Zeroes and Ones

In [16]:
# All zeros

zeros = torch.zeros(3, 4)
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [17]:
# All ones
ones = torch.ones(3, 4)
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [18]:
ones.dtype

torch.float32

### Range of tensors

In [19]:
# Range

one_to_ten = torch.arange(0, 11, step=2)
one_to_ten

tensor([ 0,  2,  4,  6,  8, 10])

In [20]:
# Creating tensors like

ten_zeros = torch.zeros_like(one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0])

### Tensor datatypes

In [21]:
# Float 32 tensor
float_32_tensor = torch.tensor([3.0, 6.0, 9.0], dtype=None, device=None, requires_grad=False)
float_32_tensor, float_32_tensor.dtype

(tensor([3., 6., 9.]), torch.float32)

In [22]:
# Float 16 tensor
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [23]:
# WILL MAYBE GIVE ERROR FOR DIFFERENT DATATYPES
int_32_tensor = torch.tensor([3, 6, 8], dtype=torch.int32)
int_32_tensor

int_32_tensor * float_32_tensor

tensor([ 9., 36., 72.])

In [24]:
# Create a tensor

some_tensor = torch.rand(3, 4)

some_tensor

tensor([[0.5573, 0.3411, 0.9878, 0.2221],
        [0.9314, 0.7518, 0.2880, 0.3084],
        [0.8099, 0.5328, 0.6639, 0.7169]])

In [25]:
# Find out details about it

print(f"Shape of tensor: {some_tensor.shape}")
print(f"Datatype of tensor: {some_tensor.dtype}")
print(f"Device tensor is stored on: {some_tensor.device}") # will default to CPU

Shape of tensor: torch.Size([3, 4])
Datatype of tensor: torch.float32
Device tensor is stored on: cpu


### Manipulating tensors (tensor operations)

In [26]:
# Addition

tensor = torch.tensor([1,2,3])
tensor + 10

tensor([11, 12, 13])

In [27]:
# Multiply

tensor * 10

tensor([10, 20, 30])

In [28]:
# Subtraction

(tensor * 10) - 10

tensor([ 0, 10, 20])

In [29]:
# Division

(tensor * 100) / 10

tensor([10., 20., 30.])

In [30]:
# Matrix multiplication (dot product)

torch.matmul(tensor, tensor), 1*1 + 2*2 + 3*3

(tensor(14), 14)

In [31]:
%%time

value = 0

for i in range(len(tensor)):
  value += tensor[i] * tensor[i]

print(value)

tensor(14)
CPU times: user 1.27 ms, sys: 57 µs, total: 1.33 ms
Wall time: 3.55 ms


In [32]:
# Pytorch functions are usually faster

%%time

torch.matmul(tensor, tensor)

CPU times: user 20 µs, sys: 5 µs, total: 25 µs
Wall time: 27.9 µs


tensor(14)

In [33]:
# shape error

tensor_1 = torch.tensor([[1,2], [3,4], [5,6]])
tensor_2 = torch.tensor([[7,10], [8,11], [9,12]])

# torch.mm(tensor_1, tensor_2) # Also torch.mm (alias for matmul)

In [34]:
# To fix above errors, we can change shape using transpose

tensor_2.T

tensor([[ 7,  8,  9],
        [10, 11, 12]])

In [35]:
print(tensor_2)

tensor([[ 7, 10],
        [ 8, 11],
        [ 9, 12]])


In [36]:
# Shape error fixed

torch.mm(tensor_1, tensor_2.T)

tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])

### Tensor aggregation (min, max, sum, mean)

In [37]:
# Create a tensor

x = torch.arange(0, 100, step=10)

x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [38]:
# Find the min
torch.min(x), x.min()

(tensor(0), tensor(0))

In [39]:
# Find the max
torch.max(x), x.max()

(tensor(90), tensor(90))

In [40]:
# Find the average/arithmetic mean - note: tensor type - float32

torch.mean(x.type(torch.float32)), x.type(torch.float32).mean()

(tensor(45.), tensor(45.))

In [41]:
# Find the sum

torch.sum(x), x.sum()

(tensor(450), tensor(450))

In [42]:
# Finding the positional min

x.argmin(), x[0]

(tensor(0), tensor(0))

In [43]:
# Finding the positional max

x.argmax(), x[9]

(tensor(9), tensor(90))

### Reshaping, stacking, squeezing & unsqueezing tensors

In [44]:
# Create a tensor
x = torch.arange(1, 11)

x, x.shape

(tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10]), torch.Size([10]))

In [45]:
# Add an extra dimension
x_reshaped = x.reshape(2, 5)
x_reshaped, x_reshaped.shape

(tensor([[ 1,  2,  3,  4,  5],
         [ 6,  7,  8,  9, 10]]),
 torch.Size([2, 5]))

In [46]:
# Change the view - (views share same memory as original tensor)
print(x, x.shape)
z = x.view(1, 10)

z, z.shape

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10]) torch.Size([10])


(tensor([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10]]), torch.Size([1, 10]))

In [47]:
# z changes x

z[:, 0] = 5
z, x

(tensor([[ 5,  2,  3,  4,  5,  6,  7,  8,  9, 10]]),
 tensor([ 5,  2,  3,  4,  5,  6,  7,  8,  9, 10]))

In [56]:
# Stack tensors on top of each other

x_stack = torch.stack([x, x, x, x], dim=0)
x_stack

tensor([[ 5,  2,  3,  4,  5,  6,  7,  8,  9, 10],
        [ 5,  2,  3,  4,  5,  6,  7,  8,  9, 10],
        [ 5,  2,  3,  4,  5,  6,  7,  8,  9, 10],
        [ 5,  2,  3,  4,  5,  6,  7,  8,  9, 10]])

In [69]:
# Squeezing

x = x_reshaped.reshape(1, 10)
x

tensor([[ 5,  2,  3,  4,  5,  6,  7,  8,  9, 10]])

In [72]:
x_squeezed = x.squeeze()

In [78]:
# Unsqueezing

print(f"Previous target: {x_squeezed}")

x_unsqueezed = x_squeezed.unsqueeze(dim=0)
print(f"New tensor: {x_unsqueezed}")

Previous target: tensor([ 5,  2,  3,  4,  5,  6,  7,  8,  9, 10])
New tensor: tensor([[ 5,  2,  3,  4,  5,  6,  7,  8,  9, 10]])


In [84]:
# Permute - rearranges dimensions of tensor in a specified order (used for images)
# Returns view

previous_tensor = torch.tensor([1, 2, 3, 4, 5])
previous_tensor = previous_tensor.unsqueeze(dim=0)
previous_tensor.shape

previous_tensor.permute(1, 0)

tensor([[1],
        [2],
        [3],
        [4],
        [5]])

In [86]:
# Indexing

x = torch.arange(1, 10).reshape(1, 3, 3)
x

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [87]:
x[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [96]:
x[0][2][0]

tensor(7)

In [122]:
# You can also use ":" to select all of a target dimension


x[0][2][2]

# Return 3, 6, 9
x[:, :, 2]

tensor([[3, 6, 9]])

### PyTorch + NumPy

In [130]:
# NumPy array to tensor

import torch
import numpy as np

array = np.arange(1.0, 8.0)
tensor = torch.from_numpy(array) # warning: when converting tensor is type of numpy

array, tensor

(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [131]:
# Changing value of array doesn't change tensor

array = array + 1

array, tensor

(array([2., 3., 4., 5., 6., 7., 8.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [132]:
# Tensor to NumPy

tensor = torch.ones(7)
numpy_tensor = tensor.numpy()

tensor, numpy_tensor

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

In [133]:
# Changing the tensor doesn't change array

tensor = tensor + 1

tensor, numpy_tensor

(tensor([2., 2., 2., 2., 2., 2., 2.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

### Reproducibility (random out of random)

In [138]:
import torch

rand_a = torch.rand(3, 4)
rand_b = torch.rand(3, 4)

print(rand_a)
print(rand_b)

print(rand_a == rand_b)

tensor([[0.9727, 0.0850, 0.9123, 0.0246],
        [0.5071, 0.1855, 0.6742, 0.1296],
        [0.9010, 0.3385, 0.3305, 0.5049]])
tensor([[0.0597, 0.7308, 0.5129, 0.2202],
        [0.9135, 0.3289, 0.3203, 0.3722],
        [0.7700, 0.9592, 0.1317, 0.1979]])
tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])


In [142]:
# random but reproducible tensors

# set the manual seed
RANDOM_SEED = 42

torch.manual_seed(RANDOM_SEED)
rand_c = torch.rand(3, 4)

torch.manual_seed(RANDOM_SEED)
rand_d = torch.rand(3, 4)

print(rand_c)
print(rand_d)

print(rand_c == rand_d)

tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])


### Running tensors and PyTorch objects on GPUs (and making faster computations)

GPUs = faster computation on numbers, CUDA + NVIDIA + PyTorch

In [4]:
!nvidia-smi

Fri Oct  6 08:20:08 2023       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 525.105.17   Driver Version: 525.105.17   CUDA Version: 12.0     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Tesla T4            Off  | 00000000:00:04.0 Off |                    0 |
| N/A   36C    P8     9W /  70W |      0MiB / 15360MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-------

In [7]:
# Check access with PyTorch

import torch

torch.cuda.is_available()

True

In [13]:
# Setup device agnostic code

device = "cuda" if torch.cuda.is_available() else "cpu"
device

'cuda'

In [9]:
# Count number of devices

torch.cuda.device_count()

1

In [12]:
# CPU
tensor = torch.tensor([1, 2, 3])
print(tensor, tensor.device)

tensor([1, 2, 3]) cpu


In [17]:
# GPU
tensor_on_gpu = tensor.to(device)
tensor_on_gpu

tensor([1, 2, 3], device='cuda:0')

In [18]:
# Back to CPU (eg. NumPy works only with CPU)

tensor_back_to_cpu = tensor_on_gpu.cpu().numpy()
tensor_back_to_cpu

array([1, 2, 3])

### Exercises

In [26]:
import torch

In [20]:
rand_tensor = torch.rand(7, 7)
rand_tensor

tensor([[0.5976, 0.4372, 0.4313, 0.6961, 0.7747, 0.7481, 0.5471],
        [0.0182, 0.5889, 0.2561, 0.3162, 0.7431, 0.2911, 0.8269],
        [0.5398, 0.2803, 0.4033, 0.4635, 0.9476, 0.7972, 0.7341],
        [0.0360, 0.5501, 0.0690, 0.1209, 0.1253, 0.0780, 0.9004],
        [0.8500, 0.3335, 0.5807, 0.2337, 0.8074, 0.9291, 0.9145],
        [0.3695, 0.1911, 0.2380, 0.8796, 0.8647, 0.6291, 0.6343],
        [0.3568, 0.3543, 0.6905, 0.0084, 0.6948, 0.9826, 0.3648]])

In [24]:
rand_tensor_b = torch.rand(1, 7)
rand_tensor_b = rand_tensor_b.reshape(7, 1)
rand_tensor_b

tensor([[0.7286],
        [0.9148],
        [0.7174],
        [0.8493],
        [0.2286],
        [0.2367],
        [0.7233]])

In [25]:
result = torch.mm(rand_tensor, rand_tensor_b)
result

tensor([[2.4859],
        [1.8412],
        [2.2690],
        [1.3801],
        [2.6055],
        [2.1672],
        [1.7419]])